-- CreateTable
CREATE TABLE `Users` (
    `USER_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_USERNAME` VARCHAR(100) NOT NULL,
    `USER_PASSWORD` VARCHAR(255) NOT NULL,
    `USER_TOKEN` TEXT NOT NULL,
    `USER_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `USER_LAST_LOGIN` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `USER_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`USER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
