-- CreateTable
CREATE TABLE `Similarity` (
    `SIMILARITY_ID` VARCHAR(191) NOT NULL,
    `SIMILARITY_NPP` VARCHAR(10) NOT NULL,
    `SIMILARITY_FILE` VARCHAR(191) NOT NULL,
    `SIMILARITY_STATUS` TINYINT NOT NULL,
    `SIMILARITY_NOTES` TEXT NOT NULL,
    `SIMILARITY_PROCESSED_BY` VARCHAR(191) NOT NULL,
    `SIMILARITY_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `SIMILARITY_UPDATED_AT` DATETIME(3) NOT NULL,
    `SIMILARITY_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`SIMILARITY_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Similarity` ADD CONSTRAINT `Similarity_SIMILARITY_PROCESSED_BY_fkey` FOREIGN KEY (`SIMILARITY_PROCESSED_BY`) REFERENCES `Users`(`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
