### Get All Data Role ###
GET http://localhost:3000/role/


### Get Data Role By ID ###
GET http://localhost:3000/role/477f6563-1567-4cc5-99fe-8ea95307d120


### Create new role ###
POST http://localhost:3000/role
Content-Type: application/json

{
    "name": "operator-similaritas"
}


### Update data role ###
PUT http://localhost:3000/role/adcf3de3-ca8c-4217-9b91-6bda028dd3c7
Content-Type: application/json

{
    "name": "role-update"
}

### Delete data role ###
DELETE  http://localhost:3000/role/adcf3de3-ca8c-4217-9b91-6bda028dd3c7


### Destroy data role ###
DELETE  http://localhost:3000/role/delete/test


### Get All Data Deleted Role ###
GET http://localhost:3000/role/trash


### Restore Data role ###
PUT http://localhost:3000/role/trash/8925c2bb-1f02-4a86-96ee-f821fe8db466
