-- DropForeignKey
ALTER TABLE `Similarity` DROP FOREIGN KEY `Similarity_SIMILARITY_PROCESSED_BY_fkey`;

-- DropForeignKey
ALTER TABLE `Users` DROP FOREIGN KEY `Users_USER_PROFILE_fkey`;

-- AddForeignKey
ALTER TABLE `Users` ADD CONSTRAINT `Users_USER_PROFILE_fkey` FOREIGN KEY (`USER_PROFILE`) REFERENCES `Profile`(`PROFILE_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Similarity` ADD CONSTRAINT `Similarity_SIMILARITY_PROCESSED_BY_fkey` FOREIGN KEY (`SIMILARITY_PROCESSED_BY`) REFERENCES `Users`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
